### ISSUE TITLE
LeanerJS wrapper library - help regarding types.

### ISSUE THREAD

**Issue by jaymanmdev** [leaner-js/leaner#1]
Hi there!
First of all, I would like to say how impressed I am with LeanerJS. I am excited to begin using it in production applications, and I am excited to see its feature set grow!

Yesterday I started working on a nice LeanerJS wrapper which is typed and is basically a HTML DSL to build Leaner elements and components, it includes If/ElseIf/Else functionality that feels great, For functionality and Fragments. Below are a couple screenshots of how the current API works.
![image](https://github.com/user-attachments/assets/32dac868-5884-48f3-b5a5-978740538d97)
![image](https://github.com/user-attachments/assets/b2a4a180-7f13-4823-aca5-41dda1467821)

Now, I am having trouble with the Typescript side of things as I am not super well versed with Typescript yet. I am trying to build a type that covers all cases of a Leaner element (e.g. ["div", { id: "" }, ...children] etc. etc.), but this type is very recursive and in cases like spreading a list of this type it will cause typescript to error with an infinitely recursive error. (LeanerTextNodeValue is a type that denotes any serializable value or state that can be represented as stringified text.)
![image](https://github.com/user-attachments/assets/dc33d70b-4ef5-4857-8aee-ef56dc175a93)
I am wondering if you would be interested, as the creator of Leaner itself, to help build a type for me that covers all bases?

Thanks again for creating this library! Hope to hear from you soon. :)

**Comment by mimecorg** [comment]
Hello,

First of all, I appreciate your feedback a lot. I’m just starting to use Leaner in the first quasi-production project, just to figure out if it actually makes sense, and I’m fixing the small issues that I come across. So if you find any problems or missing features, please let me know.

Also I hope that you will publish your wrapper library, it looks interesting.

I tried to create a type for an element of a Leaner template, but I quickly gave up. I don’t use Typescript too much and I also have a limited knowledge of it. But I think that it should be possible to create strong types for a wrapper API like yours.
